# see the chart values defaults and descriptions here:
# https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft?modal=values
minecraftServer:
  rcon:
    enabled: false
    nodePort: 31701
    serviceType: NodePort
  version: LATEST
  nodePort: 31700
  downloadWorldUrl: /allbackups/2021-05-15-21_57_22-millie.zip
  motd: "The Soj"
  gameMode: creative
  whitelist: TransformerScorn,DispenserAD11
  ops: TransformerScorn,DispenserAD11
  forcegameMode: true
  maxWorldSize: 29999984
  serviceType: NodePort
  viewDistance: 32
  # Java VM memory reservation - make sure k8s resources matches
  memory: 2g
  enableCommandBlock: true

extraEnv:
  ENABLE_ROLLING_LOGS: true
  OVERRIDE_SERVER_PROPERTIES: true
  FORCE_WORLD_COPY: false

persistence:
  dataDir:
    enabled: true
    Size: 1Gi
    accessModes:
      - ReadWriteOnce

# run on the turing pi nodes!
nodeSelector:
  kubernetes.io/arch: arm64

extraVolumes:
  - volumeMounts:
      - name: minecraft-backup
        mountPath: /allbackups
        readOnly: true
  - volumes:
      - name: minecraft-backup
        persistentVolumeClaim:
          claimName: minecraft-backup

# kubernetes memory/cpu reservation/limits
resources:
  requests:
    memory: 2Gi
    cpu: 1
  limits:
    memory: 3Gi
    cpu: 8
