apiVersion: v1
kind: PersistentVolume
metadata:
  name: adventure-of-doom-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: adventure-of-doom
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    # this folder was originally created by nfs auto provisioning, I moved it to the 
    # pv folder and performed chown -R 1022:1022 to enable it as a permanent PV
    path: /share/k3sdata/pv/minecraft-adventure-of-doom-minecraft-datadir-pvc-8ff61874-9d8f-4f48-b07e-84c40b22d3da/
    server: 192.168.0.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adventure-of-doom-pvc
  namespace: minecraft
spec:
  storageClassName: adventure-of-doom
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi