apiVersion: v1
kind: PersistentVolume
metadata:
  name: animal-world-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: animal-world
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    # this folder was originally created by nfs auto provisioning, I moved it to the
    # pv folder and performed chown -R 1022:1022 to enable it as a permanent PV
    path: /k3sdata/pv/minecraft-animimal-world-minecraft-datadir-pvc-530cf1c1-5c80-44ec-8d2d-2248858cdc0c/
    server: 192.168.0.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: animal-world-pvc
  namespace: minecraft
spec:
  storageClassName: animal-world
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
