apiVersion: v1
kind: PersistentVolume
metadata:
  name: mansion-world-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mansion-world
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    # this folder was originally created by nfs auto provisioning, I moved it to the 
    # pv folder and performed chown -R 1022:1022 to enable it as a permanent PV
    path: /share/k3sdata/pv/minecraft-mansion-world-minecraft-datadir-pvc-2c8572fb-64ba-44b8-a39e-78aa888ec591
    server: 192.168.0.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mansion-world-pvc
  namespace: minecraft
spec:
  storageClassName: mansion-world
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi