apiVersion: v1
kind: PersistentVolume
metadata:
  name: millie-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: millie
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    # this folder was originally created by nfs auto provisioning, I moved it to the 
    # pv folder and performed chown -R 1022:1022 to enable it as a permanent PV
    path: /share/k3sdata/pv/minecraft-millie-minecraft-datadir-pvc-8bc87ade-ee2b-492b-a438-c5ac8b6c1f86
    server: 192.168.86.32
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: millie-pvc
  namespace: minecraft
spec:
  storageClassName: millie
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi