apiVersion: v1
kind: PersistentVolume
metadata:
  name: noah-dad-original-survival-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: noah-dad-original-survival
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    # this folder was originally created by nfs auto provisioning, I moved it to the
    # pv folder and performed chown -R 1022:1022 to enable it as a permanent PV
    path: /k3sdata/pv/minecraft-noah-dad-original-survival-minecraft-datadir-pvc-fbd405c4-b0e7-4e50-b2bf-487cc0216835/
    server: 192.168.0.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noah-dad-original-survival-pvc
  namespace: minecraft
spec:
  storageClassName: noah-dad-original-survival
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
