apiVersion: v1
kind: PersistentVolume
metadata:
  name: science-lab-minecraft-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: science-lab-minecraft
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    # this folder was originally created by nfs auto provisioning, I moved it to the 
    # pv folder and performed chown -R 1022:1022 to enable it as a permanent PV
    path: /share/k3sdata/pv/minecraft-science-lab-minecraft-datadir-pvc-c0439914-d609-4480-998f-8de5eca66c68
    server: 192.168.0.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: science-lab-minecraft-pvc
  namespace: minecraft
spec:
  storageClassName: science-lab-minecraft
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi