apiVersion: v1
kind: PersistentVolume
metadata:
  name: transformers-best-pv
  namespace: minecraft
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: transformers-best
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    # this folder was originally created by nfs auto provisioning, I moved it to the 
    # pv folder and performed chown -R 1022:1022 to enable it as a permanent PV
    path: /share/k3sdata/pv/minecraft-transformers-best-minecraft-datadir-pvc-db6cf952-ceed-44f1-bda2-c31d1c18a79d
    server: 192.168.0.20
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transformers-best-pvc
  namespace: minecraft
spec:
  storageClassName: transformers-best
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi