apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-loader-volume
  namespace: minecraft
  labels:
    directory: minecraft-backups
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  storageClassName: local-path
  local:
    path: /mnt/bigdisk/MinecraftBackups/
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/gknuc
              operator: In
              values:
                - ubuntu
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-loader
  namespace: minecraft
spec:
  storageClassName: local-path
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      directory: minecraft-backups