# this makes the ambassador mapping work
grafana.ini:
  server:
    # The full public facing url you use in browser, used for redirects and emails
    root_url: https://gknuc.local/grafana/

# for some reason nfs-storageclass causes grafana pod to exit 1 with no log
# so use local-path and tie to a specific server for local storage
persistence:
  enabled: true
  storageClassName: local-path

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - pi4

tolerations:
- key: "architecture"
  operator: "Equal"
  value: "arm"
  effect: "NoSchedule"