prometheus:
  prometheusSpec:
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: prometheus-pv
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
              
  