---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash-ingress
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Add https backend protocol support for ingress-nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Accept-Encoding "";
      sub_filter '<base href="/">' '<base href="/dashboard/">';
      sub_filter_once on;
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules: 
  - host: gilesk.ddns.net
    http:
      paths:
        - path: /dashboard(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: dashboard-release-kubernetes-dashboard
              port:
                number: 443
  tls:
  - hosts:
    - gilesk.ddns.net
    secretName: gilesk.ddns.net-tls
