
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-two
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 30Gi