apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storageclass # IMPORTANT pvc needs to mention this name
provisioner: k3s-nfs
parameters:
  archiveOnDelete: "true"
  namespace: default
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-pod-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      affinity:
        # I like to use the Pis (arm64) for running the cluster and keep
        # my AMD64 server(s) for heavy lifting
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
      serviceAccountName: nfs-pod-provisioner-sa
      containers:
        - name: nfs-client-provisioner
          image: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner:v4.0.0
          volumeMounts:
            - name: nfs-provisioner-v
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME # do not change
              value: k3s-nfs # SAME AS PROVISONER NAME VALUE IN STORAGECLASS
            - name: NFS_SERVER # do not change
              value: 192.168.0.20 # UPDATE WITH NFS SERVER IP OR NAME
            - name: NFS_PATH # do not change
              value: /k3sdata/auto-pvcs # UPDATE WITH PATH ON NFS SERVER FOR ROOT OF PVs
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 500Mi
      volumes:
       - name: nfs-provisioner-v # same as volumemounts name
         nfs:
           server: 192.168.0.20 # UPDATE WITH NFS SERVER IP OR NAME
           path: /k3sdata/auto-pvcs # UPDATE WITH PATH ON NFS SERVER FOR ROOT OF PVs
