#!/bin/bash

# a script to launch a set of windows in the zellij terminal muxer for monitoring 
# all the nodes in giles k8s cluster
export ZELLIJ_DIR=$(dirname "${BASH_SOURCE[0]}")

export KUBECONFIG=/home/giles/.kube/mcconfig:/home/giles/.kube/config_argus:/home/giles/.kube/config_pollux
kubectl config use-context minecraft
source ${ZELLIJ_DIR}/../../k8s-mc.sh

zellij --layout-path ${ZELLIJ_DIR}/k3s-zellij.yaml
