# list here the servers you want running.
# each server should have a corresponding minecraft helm chart values file from
# the /argocd/servers folder called <server>.yaml
minecraft_servers:
  - millie

# Argo CD destination information
destination:
  server: https://kubernetes.default.svc
  namespace: minecraft
project: kubernetes # todo a separate project would be nice for this
