---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-nfs
  namespace: admin
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      # auto cleanup the job
      ttlSecondsAfterFinished: 100000
      template:
        metadata:
          labels:
            app.kubernetes.io/name: backup-nfs
        spec:
          securityContext:
            runAsUser: 0
          restartPolicy: OnFailure
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    # nuc1 hosts the backup disk so this will improve performance
                    - nuc1
          containers:
          - image: instrumentisto/rsync-ssh:alpine3.15
            imagePullPolicy: IfNotPresent
            name: backup-nfs
            resources:
              requests:
                memory: 100Mi
                cpu: 200m
              limits:
                memory: 1000Mi
                cpu: "2"
            env:
              - name: DIRS
                value: bigdisk k3sdata
            command:
            - /bin/sh
            - -c
            - for d in $DIRS ; do sh /script/rsync-backup.sh /source/$d /backup/$d ; done
            volumeMounts:
              - name: script
                mountPath: /script
              - name: backup
                mountPath: /backup
              - name: bigdisk
                mountPath: /source/bigdisk
                readOnly: true
              - name: k3sdata
                mountPath: /source/k3sdata
                readOnly: true

          volumes:
            # use the disk directly as we run on nuc1
            - name: backup
              hostPath:
                path: /bigdisk_archive/daily_backups
            - name: bigdisk
              nfs:
                server: 192.168.0.20
                path: /bigdisk
            - name: k3sdata
              nfs:
                server: 192.168.0.20
                path: /k3sdata            
            - name: script
              configMap:
                name: rsync-backup
